name: Push config.toml to MinIO

on:
  push:
    paths:
      - "config.toml"

jobs:
  upload:
    runs-on: self-hosted
    name: Upload config.toml to MinIO

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload config.toml to MinIO bucket 'test'
        run: |
          mc cp config.toml localminio/test/config.toml
